<?php
	$rhelper = $this->helper('\Rbncha\ExtendedCms\Helper\Data');
	//{{block class="Magento\Framework\View\Element\Template" template="Magento_Cms::custom_template/template1.phtml"}} 

?>

<div class="captivatebio-template1-block-1">
	<div class="content">
		<div class="content-inner">
			<h1 class="page-heading">Sample H1 Header</h1>
			<h5>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget nunc vel lorem accumsan</h5>
			<p>Quisque vehicula elementum mi nec blandit. Phasellus ultrices aliquam dolor vel vehicula. Pellentesque sit amet mi pretium, pellentesque mi vel, auctor dolor. Cras ac vulputate augue, nec mollis tellus. Integer quis magna a libero efficitur imperdiet. Sed sed hendrerit ante. Praesent eu eleifend dui, id tincidunt lorem. Nunc vehicula sed ante in sodales. Quisque eget sagittis nulla, et elementum sem. Etiam varius egestas porta.</p>
		</div>
	</div>
  	<div class="block-image">
		<img src="<?= $rhelper->getMediaUrl('services/Captivate_Services_Globe.png')?>" alt="" />
	</div>
</div>

<div class="captivatebio-template1-content-blocks">

	<div class="captivatebio-template1-block-2">
		<div class="container">
			<div class="content">
				<div class="content-inner">
					<h1>This is a <span class="stylish"> sample </span> H2 header</h1>
					<p class="big-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget nunc vel lorem accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget nunc vel lorem accumsan</p>

					<p>Quisque vehicula elementum mi nec blandit. Phasellus ultrices aliquam dolor vel vehicula. Pellentesque sit amet mi pretium, pellentesque mi vel, auctor dolor. Cras ac vulputate augue, nec mollis tellus. Integer quis magna a libero efficitur imperdiet. Sed sed hendrerit ante. Praesent eu eleifend dui, id tincidunt lorem. Nunc vehicula sed ante in sodales. Quisque eget sagittis nulla, et elementum sem. Etiam varius egestas porta.</p>

					<a href="<?= $rhelper->getMediaUrl('documents/services/Captivate-Bio-Custom-Media-Form.pdf')?>" target="blank" class="theme-btn theme-btn-blue theme-btn-arrow">Sample Button</a>
				</div>
			</div>

			<div class="block-image">
				<img src="<?= $rhelper->getMediaUrl('services/Captivate_Services_Globe.png')?>" alt="" />
			</div>
		</div>
	</div>
	
	<div class="captivatebio-template1-block-2 captivatebio-template1-block-3">
		<div class="container">
			<div class="content">
				<div class="content-inner">
					<h1>This is a <span class="stylish"> sample </span> H2 header</h1>
					<p class="big-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget nunc vel lorem accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eget nunc vel lorem accumsan</p>

					<p>Quisque vehicula elementum mi nec blandit. Phasellus ultrices aliquam dolor vel vehicula. Pellentesque sit amet mi pretium, pellentesque mi vel, auctor dolor. Cras ac vulputate augue, nec mollis tellus. Integer quis magna a libero efficitur imperdiet. Sed sed hendrerit ante. Praesent eu eleifend dui, id tincidunt lorem. Nunc vehicula sed ante in sodales. Quisque eget sagittis nulla, et elementum sem. Etiam varius egestas porta.</p>

					<a href="<?= $rhelper->getMediaUrl('documents/services/Captivate-Bio-Custom-Media-Form.pdf')?>" target="blank" class="theme-btn theme-btn-blue theme-btn-arrow">Sample Button</a>
				</div>
			</div>

			<div class="block-image">
				<img src="<?= $rhelper->getMediaUrl('services/Captivate_Services_Globe.png')?>" alt="" />
			</div>
		</div>
	</div>
	
	<div class="captivatebio-template1-block-4">
		<div class="content">
			<h1>This is a Sample H3 Header</h1>
			<p class="big-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consectetur adipiscing elit. Morbi eget nunc vel lorem accumsan</p>
		</div>
	</div>
	
	<div class="captivatebio-template1-block-5">
		<div class="content">
			<div class="row">
				<div class="col">
					<h5>Sample H4 Header</h5>
					<ul class="disc">
						<li>Quisque vehicula elementum mi nec blandit. Phasellus ultrices aliquam.</li>
						<li>Quisque vehicula elementum mi nec blandit. Phasellus.</li>
						<li>Quisque vehicula elementum mi nec blandit.</li>
						<li>Quisque vehicula elementum mi.</li>
						<li>Quisque vehicula elementum mi.</li>
					</ul>
				</div>
				<div class="col">
					<h5>Sample H4 Header</h5>
					<ul class="check">
						<li>Quisque vehicula elementum mi nec blandit. Phasellus ultrices aliquam.</li>
						<li>Quisque vehicula elementum mi nec blandit. Phasellus.</li>
						<li>Quisque vehicula elementum mi nec blandit.</li>
						<li>Quisque vehicula elementum mi.</li>
						<li>Quisque vehicula elementum mi.</li>
					</ul>
				</div>
				<div class="col">
					<h5>Sample H4 Header</h5>
					<ol class="number">
						<li>Quisque vehicula elementum mi nec blandit. Phasellus ultrices aliquam.</li>
						<li>Quisque vehicula elementum mi nec blandit. Phasellus.</li>
						<li>Quisque vehicula elementum mi nec blandit.</li>
						<li>Quisque vehicula elementum mi.</li>
						<li>Quisque vehicula elementum mi.</li>
					</ol>
				</div>
				
			</div>
		</div>
	</div>
	
</div>


<!-- -------------------------------------------- -->
<!-- IMPORTANT! Don't move this CSS anywhere else -->
<!-- -------------------------------------------- -->
<style>
  footer.page-footer {
    margin-top: 0;
  }

  .page-wrapper {
    background: #e5ebf1;
  }
</style>